# constraints

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "2.0.0"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.0.7"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-cleanhttp"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.7.3"

[[constraint]]
  name = "github.com/coreos/go-etcd"
  version = "2.0.0"

[[constraint]]
  name = "gopkg.in/coreos/go-etcd.v0"
  version = "0.4.6"

[[constraint]]
  branch = "master"
  name = "github.com/samuel/go-zookeeper"

[[constraint]]
  branch = "master"
  name = "github.com/gliderlabs/pkg"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

# overrides

[[override]]
  name = "github.com/docker/docker"
  revision = "a422774e593b33bd287d9890544ad9e09b380d8c"

[[override]]
  branch = "master"
  name = "github.com/Azure/go-ansiterm"

# prune

[prune]
  go-tests = true
  unused-packages = true
